name: beamcoda_jobs_flutter
description: BeamCoda Jobs Portal Flutter Application

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.3.2
  flutter_launcher_icons: ^0.10.0
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  http: ^0.13.5
  device_info_plus: ^5.0.1
  firebase_core: ^2.1.0
  firebase_messaging: ^14.0.2
  intl: ^0.17.0
  url_launcher: ^6.1.6
  image_picker: ^0.8.6
  file_picker: ^5.2.2
  flutter_datetime_picker: ^1.5.1
  change_app_package_name: ^1.1.0
  flutter_bloc: ^8.1.1
  path: ^1.8.2
  bloc: ^8.1.0
  google_sign_in: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_flavorizr: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_fonts/
    - assets/images/
    - assets/illustrations/
    - assets/icons/
    - assets/icons/sharer/

flavorizr:
  app:
    android:
      flavorDimensions: "app"
    ios:


  flavors:
    production:
      # Flavor-specific configuration for the production flavor
      flavorizr:
        name: "Production"
        description: "Production environment"
        colors:
          primary: Colors.blue
        # Android-specific configuration
        android:
          applicationId: "com.example.beamcoda_jobs.production"
        # iOS-specific configuration
        ios:
          bundleId: "com.example.beamcoda_jobs.production"
          config: "assets/files/firebase/GoogleService-Info-prod.plist"
      #          Add any other iOS-specific settings here

      development:
        # Flavor-specific configuration for the development flavor
        flavorizr:
          name: "Development"
          description: "Development environment"
          colors:
            primary: Colors.red
          # Android-specific configuration
          android:
            applicationId: "com.example.beamcoda_jobs.dev"
          # iOS-specific configuration
          ios:
            bundleId: "com.example.beamcoda_jobs.dev"
            config: "assets/files/firebase/GoogleService-Info-dev.plist"
  #            Add any other iOS-specific settings here