// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3GdkkLIhEj91GL-BdrEdQnItdQqy1mRU',
    appId: '1:118594946501:web:9031435f0729740e4f37ac',
    messagingSenderId: '118594946501',
    projectId: 'cari-jobs-d90a8',
    authDomain: 'cari-jobs-d90a8.firebaseapp.com',
    storageBucket: 'cari-jobs-d90a8.appspot.com',
    measurementId: 'G-3Y170CZ5JC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAviR6P8usxMmK5iVflgVGPQ0X6JcrrWdU',
    appId: '1:118594946501:android:256e2d44f152431d4f37ac',
    messagingSenderId: '118594946501',
    projectId: 'cari-jobs-d90a8',
    storageBucket: 'cari-jobs-d90a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7ONHsvoXYWPCewlWctVxUw6O6v5PFtqE',
    appId: '1:118594946501:ios:03eb1df54fbeef144f37ac',
    messagingSenderId: '118594946501',
    projectId: 'cari-jobs-d90a8',
    storageBucket: 'cari-jobs-d90a8.appspot.com',
    iosBundleId: 'com.tenstar.carijobs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7ONHsvoXYWPCewlWctVxUw6O6v5PFtqE',
    appId: '1:118594946501:ios:03eb1df54fbeef144f37ac',
    messagingSenderId: '118594946501',
    projectId: 'cari-jobs-d90a8',
    storageBucket: 'cari-jobs-d90a8.appspot.com',
    iosBundleId: 'com.tenstar.carijobs',
  );
}
