// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuEF0HOLbOlcUW3TRLC5z8U5K7ULJ3Ii4',
    appId: '1:883383557401:web:9169ea6300e1d2a4757988',
    messagingSenderId: '883383557401',
    projectId: 'codajobs-605ab',
    authDomain: 'codajobs-605ab.firebaseapp.com',
    storageBucket: 'codajobs-605ab.appspot.com',
    measurementId: 'G-5M4VEXHSV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfZehSv3DMTJfcgit80KxPjq_LMXA9wok',
    appId: '1:883383557401:android:8c24bf7e177307da757988',
    messagingSenderId: '883383557401',
    projectId: 'codajobs-605ab',
    storageBucket: 'codajobs-605ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXiE64BllLI2NHCciJmEeygS8oVO1j5NI',
    appId: '1:883383557401:ios:77f4c18010d1f82b757988',
    messagingSenderId: '883383557401',
    projectId: 'codajobs-605ab',
    storageBucket: 'codajobs-605ab.appspot.com',
    iosBundleId: 'com.example.beamcodaJobsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXiE64BllLI2NHCciJmEeygS8oVO1j5NI',
    appId: '1:883383557401:ios:77f4c18010d1f82b757988',
    messagingSenderId: '883383557401',
    projectId: 'codajobs-605ab',
    storageBucket: 'codajobs-605ab.appspot.com',
    iosBundleId: 'com.example.beamcodaJobsFlutter',
  );
}
